//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelEntities : DbContext
    {
        public ModelEntities()
            : base("name=ModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_G_ALERTAS> T_G_ALERTAS { get; set; }
        public DbSet<T_G_ALERTAS_RENOVACION_CARNET> T_G_ALERTAS_RENOVACION_CARNET { get; set; }
        public DbSet<T_G_ALERTAS_RENOVACION_ITV> T_G_ALERTAS_RENOVACION_ITV { get; set; }
        public DbSet<T_G_ALERTAS_ROBO> T_G_ALERTAS_ROBO { get; set; }
        public DbSet<T_G_ALERTAS_SOLICITUD_SOLRED> T_G_ALERTAS_SOLICITUD_SOLRED { get; set; }
        public DbSet<T_G_DOCUMENTACION> T_G_DOCUMENTACION { get; set; }
        public DbSet<T_G_DOCUMENTACION_VEHICULO> T_G_DOCUMENTACION_VEHICULO { get; set; }
        public DbSet<T_G_HIST_ALERTAS> T_G_HIST_ALERTAS { get; set; }
        public DbSet<T_G_HIST_CAMBIOS_CONDUCTOR> T_G_HIST_CAMBIOS_CONDUCTOR { get; set; }
        public DbSet<T_G_MENUS> T_G_MENUS { get; set; }
        public DbSet<T_G_USUARIOS> T_G_USUARIOS { get; set; }
        public DbSet<T_G_USUARIOS_CECO> T_G_USUARIOS_CECO { get; set; }
        public DbSet<T_G_USUARIOS_DELEGACION> T_G_USUARIOS_DELEGACION { get; set; }
        public DbSet<T_G_USUARIOS_DIR_TERRITORIAL> T_G_USUARIOS_DIR_TERRITORIAL { get; set; }
        public DbSet<T_G_USUARIOS_EMPRESAS> T_G_USUARIOS_EMPRESAS { get; set; }
        public DbSet<T_M_ACCIONES> T_M_ACCIONES { get; set; }
        public DbSet<T_M_CATEGORIAS> T_M_CATEGORIAS { get; set; }
        public DbSet<T_M_ESTADOS> T_M_ESTADOS { get; set; }
        public DbSet<T_M_PERFILES> T_M_PERFILES { get; set; }
        public DbSet<T_M_TIPOS_ALERTAS> T_M_TIPOS_ALERTAS { get; set; }
        public DbSet<T_M_TIPOS_SOLICITUD_SOLRED> T_M_TIPOS_SOLICITUD_SOLRED { get; set; }
        public DbSet<T_R_PERFILES_MENU> T_R_PERFILES_MENU { get; set; }
        public DbSet<T_G_ALERTAS_OTRAS_NOTIFICACIONES> T_G_ALERTAS_OTRAS_NOTIFICACIONES { get; set; }
        public DbSet<T_M_TIPOS_CLASIFICACION> T_M_TIPOS_CLASIFICACION { get; set; }
        public DbSet<T_G_GESTORES_FLOTA> T_G_GESTORES_FLOTA { get; set; }
        public DbSet<T_R_ESTADOS_ACCION> T_R_ESTADOS_ACCION { get; set; }
        public DbSet<T_G_VIA_VERDE_EXTRACTOS> T_G_VIA_VERDE_EXTRACTOS { get; set; }
        public DbSet<T_G_VIA_VERDE_IDENTIFICADORES> T_G_VIA_VERDE_IDENTIFICADORES { get; set; }
        public DbSet<T_M_CLIENTES> T_M_CLIENTES { get; set; }
        public DbSet<T_G_VIA_VERDE_TRANSACCIONES> T_G_VIA_VERDE_TRANSACCIONES { get; set; }
        public DbSet<T_G_TELEFONOS_FRECUENTES> T_G_TELEFONOS_FRECUENTES { get; set; }
        public DbSet<T_M_CATEGORIA_PREGUNTAS> T_M_CATEGORIA_PREGUNTAS { get; set; }
        public DbSet<T_G_PREGUNTAS_FRECUENTES> T_G_PREGUNTAS_FRECUENTES { get; set; }
        public DbSet<T_M_MARCA_VEHICULOS> T_M_MARCA_VEHICULOS { get; set; }
        public DbSet<T_M_MODELOS_VEHICULO> T_M_MODELOS_VEHICULO { get; set; }
        public DbSet<T_M_RUTA_VEHICULOS> T_M_RUTA_VEHICULOS { get; set; }
        public DbSet<T_M_TIPOS_CARBURANTE> T_M_TIPOS_CARBURANTE { get; set; }
        public DbSet<T_M_TIPOS_VEHICULO> T_M_TIPOS_VEHICULO { get; set; }
        public DbSet<T_M_UBICACIONES> T_M_UBICACIONES { get; set; }
        public DbSet<T_M_TIPO_SEGURO_VEHICULO> T_M_TIPO_SEGURO_VEHICULO { get; set; }
        public DbSet<T_M_TIPO_TARJETA_COMBUSTIBLE> T_M_TIPO_TARJETA_COMBUSTIBLE { get; set; }
        public DbSet<V_ALERTAS_CECOS_DELEGACION> V_ALERTAS_CECOS_DELEGACION { get; set; }
        public DbSet<V_TARJETAS_COMBUSTIBLE_EMPRESAS> V_TARJETAS_COMBUSTIBLE_EMPRESAS { get; set; }
        public DbSet<ECAR_Datos_Conductor> ECAR_Datos_Conductor { get; set; }
        public DbSet<ECAR_Tipo_Liquidacion> ECAR_Tipo_Liquidacion { get; set; }
        public DbSet<ECAR_Datos_Vehiculo> ECAR_Datos_Vehiculo { get; set; }
        public DbSet<ECAR_Datos_ITV> ECAR_Datos_ITV { get; set; }
        public DbSet<TMP_RENOVACION_ITV> TMP_RENOVACION_ITV { get; set; }
        public DbSet<T_G_HIST_CAMBIOS_TARJETA> T_G_HIST_CAMBIOS_TARJETA { get; set; }
        public DbSet<T_G_HIST_CAMBIOS_CENTRO_COSTE> T_G_HIST_CAMBIOS_CENTRO_COSTE { get; set; }
        public DbSet<ECAR_Datos_SolRed> ECAR_Datos_SolRed { get; set; }
        public DbSet<T_G_ALERTAS_CAMBIO_CONDUCTOR> T_G_ALERTAS_CAMBIO_CONDUCTOR { get; set; }
        public DbSet<T_G_ALERTAS_MULTA_CONFIRMACION_CONDUCTOR> T_G_ALERTAS_MULTA_CONFIRMACION_CONDUCTOR { get; set; }
        public DbSet<T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTOR> T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTOR { get; set; }
        public DbSet<T_G_DATOS_LEASING> T_G_DATOS_LEASING { get; set; }
        public DbSet<T_M_CORRESPONDENCIA_COD_CLI_EMPRESA_TKE> T_M_CORRESPONDENCIA_COD_CLI_EMPRESA_TKE { get; set; }
        public DbSet<T_G_TARJETA_COMBUSTIBLE> T_G_TARJETA_COMBUSTIBLE { get; set; }
        public DbSet<T_M_CUENTAS_CONTABLES> T_M_CUENTAS_CONTABLES { get; set; }
        public DbSet<T_M_TIPOS_COSTE> T_M_TIPOS_COSTE { get; set; }
        public DbSet<T_R_TIPOSCOSTE_CUENTA_CONTABLE> T_R_TIPOSCOSTE_CUENTA_CONTABLE { get; set; }
        public DbSet<T_M_EMPRESAS_VEHICULOS> T_M_EMPRESAS_VEHICULOS { get; set; }
        public DbSet<T_M_TARJETAS_CONBUSTIBLE> T_M_TARJETAS_CONBUSTIBLE { get; set; }
        public DbSet<T_G_ALERTAS_MULTA> T_G_ALERTAS_MULTA { get; set; }
        public DbSet<T_G_HIST_CAMBIOS_EMPRESA> T_G_HIST_CAMBIOS_EMPRESA { get; set; }
        public DbSet<ECAR_Datos_Multas> ECAR_Datos_Multas { get; set; }
        public DbSet<V_CONDUCTORES_USUARIOS_SAP> V_CONDUCTORES_USUARIOS_SAP { get; set; }
    }
}
