//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPHR_Empresas
    {
        public SAPHR_Empresas()
        {
            this.SAPHR_Delegaciones = new HashSet<SAPHR_Delegaciones>();
            this.SAPHR_DireccionesTerritoriales = new HashSet<SAPHR_DireccionesTerritoriales>();
            this.SAPHR_DireccionesArea = new HashSet<SAPHR_DireccionesArea>();
            this.SAPHR_CentrosCoste = new HashSet<SAPHR_CentrosCoste>();
            this.SAPHR_UnidadesOrganizativas = new HashSet<SAPHR_UnidadesOrganizativas>();
        }
    
        public int CodigoEmpresa { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<SAPHR_Delegaciones> SAPHR_Delegaciones { get; set; }
        public virtual ICollection<SAPHR_DireccionesTerritoriales> SAPHR_DireccionesTerritoriales { get; set; }
        public virtual ICollection<SAPHR_DireccionesArea> SAPHR_DireccionesArea { get; set; }
        public virtual ICollection<SAPHR_CentrosCoste> SAPHR_CentrosCoste { get; set; }
        public virtual ICollection<SAPHR_UnidadesOrganizativas> SAPHR_UnidadesOrganizativas { get; set; }
    }
}
