//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_G_DOCUMENTACION_VEHICULO
    {
        public int ID_DOCUMENTO { get; set; }
        public string MATRICULA { get; set; }
        public string DESCRIPCION { get; set; }
        public string FICHERO { get; set; }
        public System.DateTime FECHA_ALTA { get; set; }
        public int ID_TIPO_ALERTA { get; set; }
    
        public virtual T_M_TIPOS_ALERTAS T_M_TIPOS_ALERTAS { get; set; }
    }
}
