//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_G_VIA_VERDE_IDENTIFICADORES
    {
        public T_G_VIA_VERDE_IDENTIFICADORES()
        {
            this.T_G_VIA_VERDE_TRANSACCIONES = new HashSet<T_G_VIA_VERDE_TRANSACCIONES>();
        }
    
        public int ID_IDENTIFICADOR { get; set; }
        public string IDENTIFICADOR { get; set; }
        public string ID_EXTRACTO { get; set; }
        public string MATRICULA { get; set; }
        public string REF_PAGO { get; set; }
        public decimal TOTAL { get; set; }
    
        public virtual ICollection<T_G_VIA_VERDE_TRANSACCIONES> T_G_VIA_VERDE_TRANSACCIONES { get; set; }
    }
}
