//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTOR
    {
        public int ID_ALERTA { get; set; }
        public int COD_CONDUCTOR { get; set; }
        public string DNI { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string CP { get; set; }
        public string PROVINCIA { get; set; }
        public string POBLACION { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO_CARNET { get; set; }
    
        public virtual T_G_ALERTAS T_G_ALERTAS { get; set; }
    }
}
