//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_TIPOS_SOLICITUD_SOLRED
    {
        public T_M_TIPOS_SOLICITUD_SOLRED()
        {
            this.T_G_ALERTAS_SOLICITUD_SOLRED = new HashSet<T_G_ALERTAS_SOLICITUD_SOLRED>();
        }
    
        public int ID_TIPO_SOLICITUD_SOLRED { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<T_G_ALERTAS_SOLICITUD_SOLRED> T_G_ALERTAS_SOLICITUD_SOLRED { get; set; }
    }
}
