//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_TIPO_TARJETA_COMBUSTIBLE
    {
        public T_M_TIPO_TARJETA_COMBUSTIBLE()
        {
            this.T_M_TARJETAS_CONBUSTIBLE = new HashSet<T_M_TARJETAS_CONBUSTIBLE>();
        }
    
        public int ID_TARJETA_COMBUSTIBLE { get; set; }
        public string DESCRIPCION { get; set; }
        public bool BAJA { get; set; }
    
        public virtual ICollection<T_M_TARJETAS_CONBUSTIBLE> T_M_TARJETAS_CONBUSTIBLE { get; set; }
    }
}
