//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_CLIENTES
    {
        public T_M_CLIENTES()
        {
            this.T_G_VIA_VERDE_EXTRACTOS = new HashSet<T_G_VIA_VERDE_EXTRACTOS>();
        }
    
        public string ID_CLIENTE { get; set; }
        public string NIF { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string LOCALIDAD { get; set; }
        public string CODIGO_POSTAL { get; set; }
    
        public virtual ICollection<T_G_VIA_VERDE_EXTRACTOS> T_G_VIA_VERDE_EXTRACTOS { get; set; }
    }
}
