//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_ACCIONES
    {
        public T_M_ACCIONES()
        {
            this.T_G_ALERTAS = new HashSet<T_G_ALERTAS>();
            this.T_G_HIST_ALERTAS = new HashSet<T_G_HIST_ALERTAS>();
            this.T_R_ESTADOS_ACCION = new HashSet<T_R_ESTADOS_ACCION>();
        }
    
        public int ID_ACCION { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<T_G_ALERTAS> T_G_ALERTAS { get; set; }
        public virtual ICollection<T_G_HIST_ALERTAS> T_G_HIST_ALERTAS { get; set; }
        public virtual ICollection<T_R_ESTADOS_ACCION> T_R_ESTADOS_ACCION { get; set; }
    }
}
