//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_CUENTAS_CONTABLES
    {
        public T_M_CUENTAS_CONTABLES()
        {
            this.T_R_TIPOSCOSTE_CUENTA_CONTABLE = new HashSet<T_R_TIPOSCOSTE_CUENTA_CONTABLE>();
        }
    
        public string CUENTA_CONTABLE { get; set; }
        public string NOMBRE_CUENTA { get; set; }
    
        public virtual ICollection<T_R_TIPOSCOSTE_CUENTA_CONTABLE> T_R_TIPOSCOSTE_CUENTA_CONTABLE { get; set; }
    }
}
