//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_R_PERFILES_MENU
    {
        public int ID_PERFIL { get; set; }
        public int ID_MENU { get; set; }
        public bool B_ACTIVO { get; set; }
    
        public virtual T_G_MENUS T_G_MENUS { get; set; }
        public virtual T_M_PERFILES T_M_PERFILES { get; set; }
    }
}
