//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_RENOVACION_ITV
    {
        public int NUM_LINEA { get; set; }
        public string LOGIN { get; set; }
        public int ID { get; set; }
        public string MATRICULA { get; set; }
        public Nullable<System.DateTime> FECHA_ITV { get; set; }
        public Nullable<System.DateTime> FECHA_CADUCIDAD_ITV { get; set; }
        public string FICHERO_ITV { get; set; }
        public string TIPO_ARCHIVO { get; set; }
        public bool LINEA_NUEVA { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public Nullable<double> TARIFA { get; set; }
        public Nullable<double> TASA { get; set; }
        public Nullable<double> IMPUESTO_CIRCULACIÓN { get; set; }
        public Nullable<double> PR_CONSERVACION { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<bool> ITV_PASADA { get; set; }
    }
}
