//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_ECAR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CONDUCTORES_USUARIOS_SAP
    {
        public int Cod_Conductor { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento_Carnet { get; set; }
        public Nullable<bool> Personal_Interno { get; set; }
        public string Tlf { get; set; }
        public string Movil { get; set; }
        public Nullable<System.DateTime> Fecha_Carnet { get; set; }
        public Nullable<int> Num_Empleado { get; set; }
        public Nullable<int> Num_Empleado_SAP { get; set; }
        public string CentroCoste { get; set; }
        public string CentroCoste_SAP { get; set; }
        public Nullable<int> ID_EMPRESA_SAP { get; set; }
        public string NombreEmpresa { get; set; }
        public string Direccion { get; set; }
        public string Direccion_SAP { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento_SAP { get; set; }
        public string Cod_Postal { get; set; }
        public string Cod_Postal_SAP { get; set; }
        public string Poblacion { get; set; }
        public string Poblacion_SAP { get; set; }
        public string Provincia { get; set; }
        public string Provincia_SAP { get; set; }
        public string Nombre { get; set; }
        public string Nombre_SAP { get; set; }
        public string Apellidos { get; set; }
        public string Apellidos_SAP { get; set; }
        public string DNI_CONDUCTOR { get; set; }
        public string DNI_SAP { get; set; }
        public string Email { get; set; }
        public string Email_SAP { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<bool> Baja { get; set; }
        public Nullable<bool> PendienteDefinir { get; set; }
        public string NombreCECO { get; set; }
        public Nullable<int> IDTipoDocIdentificacion { get; set; }
        public string NumeroCarnetConducir { get; set; }
    }
}
