//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;


using System.Collections.Generic;
using TK_ECAR.Domain.DomainModel;

namespace TK_ECAR.Domain.Specifications
{
    
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("GeneratedCode","1.0")]
    
    [Serializable]
    public partial class ECAR_Datos_ITVSpecification : ISpecification<ECAR_Datos_ITV>
    {
    
        public Nullable<int> Id
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> IdIN
    	{
    		get;
    		set;
    	}
    
        public string Matricula
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> MatriculaIN
    	{
    		get;
    		set;
    	}
    
    	public string MatriculaContains
    	{
    		get;
    		set;
    	}
    	
    	public string MatriculaStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string MatriculaEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public Nullable<System.DateTime> Ultima_ITV
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<System.DateTime>> Ultima_ITVIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<System.DateTime> Ultima_ITVFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<System.DateTime> Ultima_ITVTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    	public Nullable<System.DateTime> Ultima_ITVFromOrNull
        {
            get;
            set;
        }
    
                    
        public Nullable<System.DateTime> Ultima_ITVToOrNull
        {
            get;
            set;
        }
    		
    
        public Nullable<System.DateTime> Vto_ITV
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<System.DateTime>> Vto_ITVIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<System.DateTime> Vto_ITVFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<System.DateTime> Vto_ITVTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    	public Nullable<System.DateTime> Vto_ITVFromOrNull
        {
            get;
            set;
        }
    
                    
        public Nullable<System.DateTime> Vto_ITVToOrNull
        {
            get;
            set;
        }
    		
    
        public Nullable<double> Tarifa
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<double>> TarifaIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<double> TarifaFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<double> TarifaTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    
        public Nullable<double> Tasa
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<double>> TasaIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<double> TasaFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<double> TasaTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    
        public Nullable<double> Importe
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<double>> ImporteIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<double> ImporteFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<double> ImporteTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    
        public Nullable<double> Impuesto_Circulacion
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<double>> Impuesto_CirculacionIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<double> Impuesto_CirculacionFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<double> Impuesto_CirculacionTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    
        public Nullable<double> Pr_Conservacion
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<double>> Pr_ConservacionIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<double> Pr_ConservacionFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<double> Pr_ConservacionTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    
        public string Otros
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> OtrosIN
    	{
    		get;
    		set;
    	}
    
    	public string OtrosContains
    	{
    		get;
    		set;
    	}
    	
    	public string OtrosStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string OtrosEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public Nullable<System.DateTime> Falta
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<System.DateTime>> FaltaIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<System.DateTime> FaltaFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<System.DateTime> FaltaTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    	public Nullable<System.DateTime> FaltaFromOrNull
        {
            get;
            set;
        }
    
                    
        public Nullable<System.DateTime> FaltaToOrNull
        {
            get;
            set;
        }
    		
    
        public string Fichero
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> FicheroIN
    	{
    		get;
    		set;
    	}
    
    	public string FicheroContains
    	{
    		get;
    		set;
    	}
    	
    	public string FicheroStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string FicheroEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public string TipoArchivo
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> TipoArchivoIN
    	{
    		get;
    		set;
    	}
    
    	public string TipoArchivoContains
    	{
    		get;
    		set;
    	}
    	
    	public string TipoArchivoStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string TipoArchivoEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public Nullable<System.DateTime> FechaModificacion
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<System.DateTime>> FechaModificacionIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<System.DateTime> FechaModificacionFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<System.DateTime> FechaModificacionTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    	public Nullable<System.DateTime> FechaModificacionFromOrNull
        {
            get;
            set;
        }
    
                    
        public Nullable<System.DateTime> FechaModificacionToOrNull
        {
            get;
            set;
        }
    		
    
        public string UsuarioAlta
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> UsuarioAltaIN
    	{
    		get;
    		set;
    	}
    
    	public string UsuarioAltaContains
    	{
    		get;
    		set;
    	}
    	
    	public string UsuarioAltaStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string UsuarioAltaEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public string UsuarioModificacion
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> UsuarioModificacionIN
    	{
    		get;
    		set;
    	}
    
    	public string UsuarioModificacionContains
    	{
    		get;
    		set;
    	}
    	
    	public string UsuarioModificacionStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string UsuarioModificacionEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public Nullable<bool> ITV_PASADA
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<bool>> ITV_PASADAIN
    	{
    		get;
    		set;
    	}
    
        #region Navigation Properties
    
    	public ECAR_Datos_VehiculoSpecification ECAR_Datos_Vehiculo
        {
            get;
    		set;
    	}

        #endregion

    
    	/// <summary>
    	/// Default constructor (needed for serialization)
    	/// Initializes a new instance of the <see cref="ECAR_Datos_ITVSpecification"/> class.
    	/// </summary>
    	public ECAR_Datos_ITVSpecification()
    	{
    
    	}
    
    	/// <summary>
    	/// Initializes a new instance of the <see cref="ECAR_Datos_ITVSpecification"/> class.
    	/// </summary>
    	/// <param name="initializeNavigationProperties">if set to <c>true</c> initialize navigation properties.</param>
    	public ECAR_Datos_ITVSpecification(bool initializeNavigationProperties)
    	{
    		if(!initializeNavigationProperties)
    			return;
    
    		this.ECAR_Datos_Vehiculo = new ECAR_Datos_VehiculoSpecification();
    	}
    
        #region ISpecification Members
    
    	public Expression<Func<ECAR_Datos_ITV, bool>> GetExpression()
    	{
    		Expression<Func<ECAR_Datos_ITV, bool>> expression = x => true;
    
    		if(Id.HasValue)
    			expression = expression.And(x => x.Id == Id.Value);
    
    		if(IdIN != null && IdIN.Count() > 0)
    			expression = expression.And(x => IdIN.Contains(x.Id));
    	
    		if(!string.IsNullOrWhiteSpace(Matricula))  
    			expression = expression.And(x => x.Matricula.Equals(Matricula));
    			
    		if(!string.IsNullOrWhiteSpace(MatriculaContains))  
    			expression = expression.And(x => x.Matricula.Contains(MatriculaContains));
    			
    		if(!string.IsNullOrWhiteSpace(MatriculaStartsWith))
    			expression = expression.And(x => x.Matricula.StartsWith(MatriculaStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(MatriculaEndsWith))
    			expression = expression.And(x => x.Matricula.EndsWith(MatriculaEndsWith));
    
    		if(MatriculaIN != null && MatriculaIN.Count() > 0)
    			expression = expression.And(x => MatriculaIN.Contains(x.Matricula));
    
    		if(Ultima_ITV.HasValue)
    			expression = expression.And(x => x.Ultima_ITV == Ultima_ITV.Value);
    
    		if(Ultima_ITVIN != null && Ultima_ITVIN.Count() > 0)
    			expression = expression.And(x => Ultima_ITVIN.Contains(x.Ultima_ITV));
    	
    		if(Ultima_ITVFrom.HasValue)
    			expression = expression.And(x => x.Ultima_ITV >= Ultima_ITVFrom.Value);
    			
    		if(Ultima_ITVTo.HasValue)
    			expression = expression.And(x => x.Ultima_ITV <= Ultima_ITVTo.Value);
    				
    
    		if(Ultima_ITVFromOrNull.HasValue)
                expression = expression.And(x => x.Ultima_ITV >= Ultima_ITVFromOrNull.Value || x.Ultima_ITV == null);
    
            if(Ultima_ITVToOrNull.HasValue)
                expression = expression.And(x => x.Ultima_ITV <= Ultima_ITVToOrNull.Value || x.Ultima_ITV == null);
    
    		if(Vto_ITV.HasValue)
    			expression = expression.And(x => x.Vto_ITV == Vto_ITV.Value);
    
    		if(Vto_ITVIN != null && Vto_ITVIN.Count() > 0)
    			expression = expression.And(x => Vto_ITVIN.Contains(x.Vto_ITV));
    	
    		if(Vto_ITVFrom.HasValue)
    			expression = expression.And(x => x.Vto_ITV >= Vto_ITVFrom.Value);
    			
    		if(Vto_ITVTo.HasValue)
    			expression = expression.And(x => x.Vto_ITV <= Vto_ITVTo.Value);
    				
    
    		if(Vto_ITVFromOrNull.HasValue)
                expression = expression.And(x => x.Vto_ITV >= Vto_ITVFromOrNull.Value || x.Vto_ITV == null);
    
            if(Vto_ITVToOrNull.HasValue)
                expression = expression.And(x => x.Vto_ITV <= Vto_ITVToOrNull.Value || x.Vto_ITV == null);
    
    		if(Tarifa.HasValue)
    			expression = expression.And(x => x.Tarifa == Tarifa.Value);
    
    		if(TarifaIN != null && TarifaIN.Count() > 0)
    			expression = expression.And(x => TarifaIN.Contains(x.Tarifa));
    	
    		if(TarifaFrom.HasValue)
    			expression = expression.And(x => x.Tarifa >= TarifaFrom.Value);
    			
    		if(TarifaTo.HasValue)
    			expression = expression.And(x => x.Tarifa <= TarifaTo.Value);
    				
    
    
    		if(Tasa.HasValue)
    			expression = expression.And(x => x.Tasa == Tasa.Value);
    
    		if(TasaIN != null && TasaIN.Count() > 0)
    			expression = expression.And(x => TasaIN.Contains(x.Tasa));
    	
    		if(TasaFrom.HasValue)
    			expression = expression.And(x => x.Tasa >= TasaFrom.Value);
    			
    		if(TasaTo.HasValue)
    			expression = expression.And(x => x.Tasa <= TasaTo.Value);
    				
    
    
    		if(Importe.HasValue)
    			expression = expression.And(x => x.Importe == Importe.Value);
    
    		if(ImporteIN != null && ImporteIN.Count() > 0)
    			expression = expression.And(x => ImporteIN.Contains(x.Importe));
    	
    		if(ImporteFrom.HasValue)
    			expression = expression.And(x => x.Importe >= ImporteFrom.Value);
    			
    		if(ImporteTo.HasValue)
    			expression = expression.And(x => x.Importe <= ImporteTo.Value);
    				
    
    
    		if(Impuesto_Circulacion.HasValue)
    			expression = expression.And(x => x.Impuesto_Circulacion == Impuesto_Circulacion.Value);
    
    		if(Impuesto_CirculacionIN != null && Impuesto_CirculacionIN.Count() > 0)
    			expression = expression.And(x => Impuesto_CirculacionIN.Contains(x.Impuesto_Circulacion));
    	
    		if(Impuesto_CirculacionFrom.HasValue)
    			expression = expression.And(x => x.Impuesto_Circulacion >= Impuesto_CirculacionFrom.Value);
    			
    		if(Impuesto_CirculacionTo.HasValue)
    			expression = expression.And(x => x.Impuesto_Circulacion <= Impuesto_CirculacionTo.Value);
    				
    
    
    		if(Pr_Conservacion.HasValue)
    			expression = expression.And(x => x.Pr_Conservacion == Pr_Conservacion.Value);
    
    		if(Pr_ConservacionIN != null && Pr_ConservacionIN.Count() > 0)
    			expression = expression.And(x => Pr_ConservacionIN.Contains(x.Pr_Conservacion));
    	
    		if(Pr_ConservacionFrom.HasValue)
    			expression = expression.And(x => x.Pr_Conservacion >= Pr_ConservacionFrom.Value);
    			
    		if(Pr_ConservacionTo.HasValue)
    			expression = expression.And(x => x.Pr_Conservacion <= Pr_ConservacionTo.Value);
    				
    
    	
    		if(!string.IsNullOrWhiteSpace(Otros))  
    			expression = expression.And(x => x.Otros.Equals(Otros));
    			
    		if(!string.IsNullOrWhiteSpace(OtrosContains))  
    			expression = expression.And(x => x.Otros.Contains(OtrosContains));
    			
    		if(!string.IsNullOrWhiteSpace(OtrosStartsWith))
    			expression = expression.And(x => x.Otros.StartsWith(OtrosStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(OtrosEndsWith))
    			expression = expression.And(x => x.Otros.EndsWith(OtrosEndsWith));
    
    		if(OtrosIN != null && OtrosIN.Count() > 0)
    			expression = expression.And(x => OtrosIN.Contains(x.Otros));
    
    		if(Falta.HasValue)
    			expression = expression.And(x => x.Falta == Falta.Value);
    
    		if(FaltaIN != null && FaltaIN.Count() > 0)
    			expression = expression.And(x => FaltaIN.Contains(x.Falta));
    	
    		if(FaltaFrom.HasValue)
    			expression = expression.And(x => x.Falta >= FaltaFrom.Value);
    			
    		if(FaltaTo.HasValue)
    			expression = expression.And(x => x.Falta <= FaltaTo.Value);
    				
    
    		if(FaltaFromOrNull.HasValue)
                expression = expression.And(x => x.Falta >= FaltaFromOrNull.Value || x.Falta == null);
    
            if(FaltaToOrNull.HasValue)
                expression = expression.And(x => x.Falta <= FaltaToOrNull.Value || x.Falta == null);
    	
    		if(!string.IsNullOrWhiteSpace(Fichero))  
    			expression = expression.And(x => x.Fichero.Equals(Fichero));
    			
    		if(!string.IsNullOrWhiteSpace(FicheroContains))  
    			expression = expression.And(x => x.Fichero.Contains(FicheroContains));
    			
    		if(!string.IsNullOrWhiteSpace(FicheroStartsWith))
    			expression = expression.And(x => x.Fichero.StartsWith(FicheroStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(FicheroEndsWith))
    			expression = expression.And(x => x.Fichero.EndsWith(FicheroEndsWith));
    
    		if(FicheroIN != null && FicheroIN.Count() > 0)
    			expression = expression.And(x => FicheroIN.Contains(x.Fichero));
    	
    		if(!string.IsNullOrWhiteSpace(TipoArchivo))  
    			expression = expression.And(x => x.TipoArchivo.Equals(TipoArchivo));
    			
    		if(!string.IsNullOrWhiteSpace(TipoArchivoContains))  
    			expression = expression.And(x => x.TipoArchivo.Contains(TipoArchivoContains));
    			
    		if(!string.IsNullOrWhiteSpace(TipoArchivoStartsWith))
    			expression = expression.And(x => x.TipoArchivo.StartsWith(TipoArchivoStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(TipoArchivoEndsWith))
    			expression = expression.And(x => x.TipoArchivo.EndsWith(TipoArchivoEndsWith));
    
    		if(TipoArchivoIN != null && TipoArchivoIN.Count() > 0)
    			expression = expression.And(x => TipoArchivoIN.Contains(x.TipoArchivo));
    
    		if(FechaModificacion.HasValue)
    			expression = expression.And(x => x.FechaModificacion == FechaModificacion.Value);
    
    		if(FechaModificacionIN != null && FechaModificacionIN.Count() > 0)
    			expression = expression.And(x => FechaModificacionIN.Contains(x.FechaModificacion));
    	
    		if(FechaModificacionFrom.HasValue)
    			expression = expression.And(x => x.FechaModificacion >= FechaModificacionFrom.Value);
    			
    		if(FechaModificacionTo.HasValue)
    			expression = expression.And(x => x.FechaModificacion <= FechaModificacionTo.Value);
    				
    
    		if(FechaModificacionFromOrNull.HasValue)
                expression = expression.And(x => x.FechaModificacion >= FechaModificacionFromOrNull.Value || x.FechaModificacion == null);
    
            if(FechaModificacionToOrNull.HasValue)
                expression = expression.And(x => x.FechaModificacion <= FechaModificacionToOrNull.Value || x.FechaModificacion == null);
    	
    		if(!string.IsNullOrWhiteSpace(UsuarioAlta))  
    			expression = expression.And(x => x.UsuarioAlta.Equals(UsuarioAlta));
    			
    		if(!string.IsNullOrWhiteSpace(UsuarioAltaContains))  
    			expression = expression.And(x => x.UsuarioAlta.Contains(UsuarioAltaContains));
    			
    		if(!string.IsNullOrWhiteSpace(UsuarioAltaStartsWith))
    			expression = expression.And(x => x.UsuarioAlta.StartsWith(UsuarioAltaStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(UsuarioAltaEndsWith))
    			expression = expression.And(x => x.UsuarioAlta.EndsWith(UsuarioAltaEndsWith));
    
    		if(UsuarioAltaIN != null && UsuarioAltaIN.Count() > 0)
    			expression = expression.And(x => UsuarioAltaIN.Contains(x.UsuarioAlta));
    	
    		if(!string.IsNullOrWhiteSpace(UsuarioModificacion))  
    			expression = expression.And(x => x.UsuarioModificacion.Equals(UsuarioModificacion));
    			
    		if(!string.IsNullOrWhiteSpace(UsuarioModificacionContains))  
    			expression = expression.And(x => x.UsuarioModificacion.Contains(UsuarioModificacionContains));
    			
    		if(!string.IsNullOrWhiteSpace(UsuarioModificacionStartsWith))
    			expression = expression.And(x => x.UsuarioModificacion.StartsWith(UsuarioModificacionStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(UsuarioModificacionEndsWith))
    			expression = expression.And(x => x.UsuarioModificacion.EndsWith(UsuarioModificacionEndsWith));
    
    		if(UsuarioModificacionIN != null && UsuarioModificacionIN.Count() > 0)
    			expression = expression.And(x => UsuarioModificacionIN.Contains(x.UsuarioModificacion));
    
    		if(ITV_PASADA.HasValue)
    			expression = expression.And(x => x.ITV_PASADA == ITV_PASADA.Value);
    
    		if(ITV_PASADAIN != null && ITV_PASADAIN.Count() > 0)
    			expression = expression.And(x => ITV_PASADAIN.Contains(x.ITV_PASADA));
    		
    		//
    		// Navigation properties
    		//
    
    		if(this.ECAR_Datos_Vehiculo != null)
    		{
    			var subExpression = ECAR_Datos_Vehiculo.GetExpression();
    			expression = expression.And(x => (new[] { x.ECAR_Datos_Vehiculo }).AsQueryable().Any(subExpression));
    		}
    	
    		return expression;
    	}
    	
    	public bool IsSatisfiedBy(ECAR_Datos_ITV entity)
    	{
    		// convert single entity to a IQueryable object, 
    		// in order to be able to use lambda expressions
    		IQueryable<ECAR_Datos_ITV> entities = (new[] { entity }).AsQueryable();
    		
    		return entities.Any(this.GetExpression());
    	}
    
        public override string ToString()
        {
            return Evaluator.PartialEval(this.GetExpression()).ToString();
        }

        #endregion

    }
}
