//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;


using System.Collections.Generic;
using TK_ECAR.Domain.DomainModel;

namespace TK_ECAR.Domain.Specifications
{
    
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("GeneratedCode","1.0")]
    
    [Serializable]
    public partial class MERSY_ZONASSpecification : ISpecification<MERSY_ZONAS>
    {
    
        public Nullable<int> Sociedad
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> SociedadIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<int> SociedadFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<int> SociedadTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    
        public string IDZona
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> IDZonaIN
    	{
    		get;
    		set;
    	}
    
    	public string IDZonaContains
    	{
    		get;
    		set;
    	}
    	
    	public string IDZonaStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string IDZonaEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public string Descripcion
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> DescripcionIN
    	{
    		get;
    		set;
    	}
    
    	public string DescripcionContains
    	{
    		get;
    		set;
    	}
    	
    	public string DescripcionStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string DescripcionEndsWith
    	{
    		get;
    		set;
    	}
    
    
        #region Navigation Properties
    
    	public MERSY_USERS_ZONASSpecification MERSY_USERS_ZONAS
        {
            get;
    		set;
    	}
    
    	public SAPHR_DelegacionesSpecification SAPHR_Delegaciones
        {
            get;
    		set;
    	}

        #endregion

    
    	/// <summary>
    	/// Default constructor (needed for serialization)
    	/// Initializes a new instance of the <see cref="MERSY_ZONASSpecification"/> class.
    	/// </summary>
    	public MERSY_ZONASSpecification()
    	{
    
    	}
    
    	/// <summary>
    	/// Initializes a new instance of the <see cref="MERSY_ZONASSpecification"/> class.
    	/// </summary>
    	/// <param name="initializeNavigationProperties">if set to <c>true</c> initialize navigation properties.</param>
    	public MERSY_ZONASSpecification(bool initializeNavigationProperties)
    	{
    		if(!initializeNavigationProperties)
    			return;
    
    		this.MERSY_USERS_ZONAS = new MERSY_USERS_ZONASSpecification();
    		this.SAPHR_Delegaciones = new SAPHR_DelegacionesSpecification();
    	}
    
        #region ISpecification Members
    
    	public Expression<Func<MERSY_ZONAS, bool>> GetExpression()
    	{
    		Expression<Func<MERSY_ZONAS, bool>> expression = x => true;
    
    		if(Sociedad.HasValue)
    			expression = expression.And(x => x.Sociedad == Sociedad.Value);
    
    		if(SociedadIN != null && SociedadIN.Count() > 0)
    			expression = expression.And(x => SociedadIN.Contains(x.Sociedad));
    	
    		if(SociedadFrom.HasValue)
    			expression = expression.And(x => x.Sociedad >= SociedadFrom.Value);
    			
    		if(SociedadTo.HasValue)
    			expression = expression.And(x => x.Sociedad <= SociedadTo.Value);
    				
    
    	
    		if(!string.IsNullOrWhiteSpace(IDZona))  
    			expression = expression.And(x => x.IDZona.Equals(IDZona));
    			
    		if(!string.IsNullOrWhiteSpace(IDZonaContains))  
    			expression = expression.And(x => x.IDZona.Contains(IDZonaContains));
    			
    		if(!string.IsNullOrWhiteSpace(IDZonaStartsWith))
    			expression = expression.And(x => x.IDZona.StartsWith(IDZonaStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(IDZonaEndsWith))
    			expression = expression.And(x => x.IDZona.EndsWith(IDZonaEndsWith));
    
    		if(IDZonaIN != null && IDZonaIN.Count() > 0)
    			expression = expression.And(x => IDZonaIN.Contains(x.IDZona));
    	
    		if(!string.IsNullOrWhiteSpace(Descripcion))  
    			expression = expression.And(x => x.Descripcion.Equals(Descripcion));
    			
    		if(!string.IsNullOrWhiteSpace(DescripcionContains))  
    			expression = expression.And(x => x.Descripcion.Contains(DescripcionContains));
    			
    		if(!string.IsNullOrWhiteSpace(DescripcionStartsWith))
    			expression = expression.And(x => x.Descripcion.StartsWith(DescripcionStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(DescripcionEndsWith))
    			expression = expression.And(x => x.Descripcion.EndsWith(DescripcionEndsWith));
    
    		if(DescripcionIN != null && DescripcionIN.Count() > 0)
    			expression = expression.And(x => DescripcionIN.Contains(x.Descripcion));
    		
    		//
    		// Navigation properties
    		//
    
    		if(this.MERSY_USERS_ZONAS != null)
    		{
    			var subExpression = MERSY_USERS_ZONAS.GetExpression();
    			expression = expression.And(x => x.MERSY_USERS_ZONAS.AsQueryable().Any(subExpression));
    		}
    
    		if(this.SAPHR_Delegaciones != null)
    		{
    			var subExpression = SAPHR_Delegaciones.GetExpression();
    			expression = expression.And(x => x.SAPHR_Delegaciones.AsQueryable().Any(subExpression));
    		}
    	
    		return expression;
    	}
    	
    	public bool IsSatisfiedBy(MERSY_ZONAS entity)
    	{
    		// convert single entity to a IQueryable object, 
    		// in order to be able to use lambda expressions
    		IQueryable<MERSY_ZONAS> entities = (new[] { entity }).AsQueryable();
    		
    		return entities.Any(this.GetExpression());
    	}
    
        public override string ToString()
        {
            return Evaluator.PartialEval(this.GetExpression()).ToString();
        }

        #endregion

    }
}
