//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;


using System.Collections.Generic;
using TK_ECAR.Domain.DomainModel;

namespace TK_ECAR.Domain.Specifications
{
    
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("GeneratedCode","1.0")]
    
    [Serializable]
    public partial class SAPHR_CentrosCosteSpecification : ISpecification<SAPHR_CentrosCoste>
    {
    
        public string IdCeco
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> IdCecoIN
    	{
    		get;
    		set;
    	}
    
    	public string IdCecoContains
    	{
    		get;
    		set;
    	}
    	
    	public string IdCecoStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string IdCecoEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public string Nombre
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> NombreIN
    	{
    		get;
    		set;
    	}
    
    	public string NombreContains
    	{
    		get;
    		set;
    	}
    	
    	public string NombreStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string NombreEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public Nullable<int> Empresa
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> EmpresaIN
    	{
    		get;
    		set;
    	}
    
        public Nullable<bool> Baja
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<bool>> BajaIN
    	{
    		get;
    		set;
    	}
    
        public Nullable<System.DateTime> FechaBaja
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<System.DateTime>> FechaBajaIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<System.DateTime> FechaBajaFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<System.DateTime> FechaBajaTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    	public Nullable<System.DateTime> FechaBajaFromOrNull
        {
            get;
            set;
        }
    
                    
        public Nullable<System.DateTime> FechaBajaToOrNull
        {
            get;
            set;
        }
    		
    
        public string IdDelegacion
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> IdDelegacionIN
    	{
    		get;
    		set;
    	}
    
    	public string IdDelegacionContains
    	{
    		get;
    		set;
    	}
    	
    	public string IdDelegacionStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string IdDelegacionEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public string IdDT
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> IdDTIN
    	{
    		get;
    		set;
    	}
    
    	public string IdDTContains
    	{
    		get;
    		set;
    	}
    	
    	public string IdDTStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string IdDTEndsWith
    	{
    		get;
    		set;
    	}
    
    
        #region Navigation Properties
    
    	public SAPHR_DelegacionesSpecification SAPHR_Delegaciones
        {
            get;
    		set;
    	}
    
    	public SAPHR_DireccionesTerritorialesSpecification SAPHR_DireccionesTerritoriales
        {
            get;
    		set;
    	}
    
    	public SAPHR_EmpresasSpecification SAPHR_Empresas
        {
            get;
    		set;
    	}

        #endregion

    
    	/// <summary>
    	/// Default constructor (needed for serialization)
    	/// Initializes a new instance of the <see cref="SAPHR_CentrosCosteSpecification"/> class.
    	/// </summary>
    	public SAPHR_CentrosCosteSpecification()
    	{
    
    	}
    
    	/// <summary>
    	/// Initializes a new instance of the <see cref="SAPHR_CentrosCosteSpecification"/> class.
    	/// </summary>
    	/// <param name="initializeNavigationProperties">if set to <c>true</c> initialize navigation properties.</param>
    	public SAPHR_CentrosCosteSpecification(bool initializeNavigationProperties)
    	{
    		if(!initializeNavigationProperties)
    			return;
    
    		this.SAPHR_Delegaciones = new SAPHR_DelegacionesSpecification();
    		this.SAPHR_DireccionesTerritoriales = new SAPHR_DireccionesTerritorialesSpecification();
    		this.SAPHR_Empresas = new SAPHR_EmpresasSpecification();
    	}
    
        #region ISpecification Members
    
    	public Expression<Func<SAPHR_CentrosCoste, bool>> GetExpression()
    	{
    		Expression<Func<SAPHR_CentrosCoste, bool>> expression = x => true;
    	
    		if(!string.IsNullOrWhiteSpace(IdCeco))  
    			expression = expression.And(x => x.IdCeco.Equals(IdCeco));
    			
    		if(!string.IsNullOrWhiteSpace(IdCecoContains))  
    			expression = expression.And(x => x.IdCeco.Contains(IdCecoContains));
    			
    		if(!string.IsNullOrWhiteSpace(IdCecoStartsWith))
    			expression = expression.And(x => x.IdCeco.StartsWith(IdCecoStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(IdCecoEndsWith))
    			expression = expression.And(x => x.IdCeco.EndsWith(IdCecoEndsWith));
    
    		if(IdCecoIN != null && IdCecoIN.Count() > 0)
    			expression = expression.And(x => IdCecoIN.Contains(x.IdCeco));
    	
    		if(!string.IsNullOrWhiteSpace(Nombre))  
    			expression = expression.And(x => x.Nombre.Equals(Nombre));
    			
    		if(!string.IsNullOrWhiteSpace(NombreContains))  
    			expression = expression.And(x => x.Nombre.Contains(NombreContains));
    			
    		if(!string.IsNullOrWhiteSpace(NombreStartsWith))
    			expression = expression.And(x => x.Nombre.StartsWith(NombreStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(NombreEndsWith))
    			expression = expression.And(x => x.Nombre.EndsWith(NombreEndsWith));
    
    		if(NombreIN != null && NombreIN.Count() > 0)
    			expression = expression.And(x => NombreIN.Contains(x.Nombre));
    
    		if(Empresa.HasValue)
    			expression = expression.And(x => x.Empresa == Empresa.Value);
    
    		if(EmpresaIN != null && EmpresaIN.Count() > 0)
    			expression = expression.And(x => EmpresaIN.Contains(x.Empresa));
    
    		if(Baja.HasValue)
    			expression = expression.And(x => x.Baja == Baja.Value);
    
    		if(BajaIN != null && BajaIN.Count() > 0)
    			expression = expression.And(x => BajaIN.Contains(x.Baja));
    
    		if(FechaBaja.HasValue)
    			expression = expression.And(x => x.FechaBaja == FechaBaja.Value);
    
    		if(FechaBajaIN != null && FechaBajaIN.Count() > 0)
    			expression = expression.And(x => FechaBajaIN.Contains(x.FechaBaja));
    	
    		if(FechaBajaFrom.HasValue)
    			expression = expression.And(x => x.FechaBaja >= FechaBajaFrom.Value);
    			
    		if(FechaBajaTo.HasValue)
    			expression = expression.And(x => x.FechaBaja <= FechaBajaTo.Value);
    				
    
    		if(FechaBajaFromOrNull.HasValue)
                expression = expression.And(x => x.FechaBaja >= FechaBajaFromOrNull.Value || x.FechaBaja == null);
    
            if(FechaBajaToOrNull.HasValue)
                expression = expression.And(x => x.FechaBaja <= FechaBajaToOrNull.Value || x.FechaBaja == null);
    	
    		if(!string.IsNullOrWhiteSpace(IdDelegacion))  
    			expression = expression.And(x => x.IdDelegacion.Equals(IdDelegacion));
    			
    		if(!string.IsNullOrWhiteSpace(IdDelegacionContains))  
    			expression = expression.And(x => x.IdDelegacion.Contains(IdDelegacionContains));
    			
    		if(!string.IsNullOrWhiteSpace(IdDelegacionStartsWith))
    			expression = expression.And(x => x.IdDelegacion.StartsWith(IdDelegacionStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(IdDelegacionEndsWith))
    			expression = expression.And(x => x.IdDelegacion.EndsWith(IdDelegacionEndsWith));
    
    		if(IdDelegacionIN != null && IdDelegacionIN.Count() > 0)
    			expression = expression.And(x => IdDelegacionIN.Contains(x.IdDelegacion));
    	
    		if(!string.IsNullOrWhiteSpace(IdDT))  
    			expression = expression.And(x => x.IdDT.Equals(IdDT));
    			
    		if(!string.IsNullOrWhiteSpace(IdDTContains))  
    			expression = expression.And(x => x.IdDT.Contains(IdDTContains));
    			
    		if(!string.IsNullOrWhiteSpace(IdDTStartsWith))
    			expression = expression.And(x => x.IdDT.StartsWith(IdDTStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(IdDTEndsWith))
    			expression = expression.And(x => x.IdDT.EndsWith(IdDTEndsWith));
    
    		if(IdDTIN != null && IdDTIN.Count() > 0)
    			expression = expression.And(x => IdDTIN.Contains(x.IdDT));
    		
    		//
    		// Navigation properties
    		//
    
    		if(this.SAPHR_Delegaciones != null)
    		{
    			var subExpression = SAPHR_Delegaciones.GetExpression();
    			expression = expression.And(x => (new[] { x.SAPHR_Delegaciones }).AsQueryable().Any(subExpression));
    		}
    
    		if(this.SAPHR_DireccionesTerritoriales != null)
    		{
    			var subExpression = SAPHR_DireccionesTerritoriales.GetExpression();
    			expression = expression.And(x => (new[] { x.SAPHR_DireccionesTerritoriales }).AsQueryable().Any(subExpression));
    		}
    
    		if(this.SAPHR_Empresas != null)
    		{
    			var subExpression = SAPHR_Empresas.GetExpression();
    			expression = expression.And(x => (new[] { x.SAPHR_Empresas }).AsQueryable().Any(subExpression));
    		}
    	
    		return expression;
    	}
    	
    	public bool IsSatisfiedBy(SAPHR_CentrosCoste entity)
    	{
    		// convert single entity to a IQueryable object, 
    		// in order to be able to use lambda expressions
    		IQueryable<SAPHR_CentrosCoste> entities = (new[] { entity }).AsQueryable();
    		
    		return entities.Any(this.GetExpression());
    	}
    
        public override string ToString()
        {
            return Evaluator.PartialEval(this.GetExpression()).ToString();
        }

        #endregion

    }
}
