//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;


using System.Collections.Generic;
using TK_ECAR.Domain.DomainModel;

namespace TK_ECAR.Domain.Specifications
{
    
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("GeneratedCode","1.0")]
    
    [Serializable]
    public partial class SAPHR_UnidadesOrganizativasSpecification : ISpecification<SAPHR_UnidadesOrganizativas>
    {
    
        public string IdUniOrganizativa
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> IdUniOrganizativaIN
    	{
    		get;
    		set;
    	}
    
    	public string IdUniOrganizativaContains
    	{
    		get;
    		set;
    	}
    	
    	public string IdUniOrganizativaStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string IdUniOrganizativaEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public string Nombre
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> NombreIN
    	{
    		get;
    		set;
    	}
    
    	public string NombreContains
    	{
    		get;
    		set;
    	}
    	
    	public string NombreStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string NombreEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public Nullable<int> Empresa
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> EmpresaIN
    	{
    		get;
    		set;
    	}
    
        public Nullable<bool> Baja
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<bool>> BajaIN
    	{
    		get;
    		set;
    	}
    
        public Nullable<System.DateTime> FechaBaja
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<System.DateTime>> FechaBajaIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<System.DateTime> FechaBajaFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<System.DateTime> FechaBajaTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    	public Nullable<System.DateTime> FechaBajaFromOrNull
        {
            get;
            set;
        }
    
                    
        public Nullable<System.DateTime> FechaBajaToOrNull
        {
            get;
            set;
        }
    		
    
        #region Navigation Properties
    
    	public SAPHR_EmpresasSpecification SAPHR_Empresas
        {
            get;
    		set;
    	}

        #endregion

    
    	/// <summary>
    	/// Default constructor (needed for serialization)
    	/// Initializes a new instance of the <see cref="SAPHR_UnidadesOrganizativasSpecification"/> class.
    	/// </summary>
    	public SAPHR_UnidadesOrganizativasSpecification()
    	{
    
    	}
    
    	/// <summary>
    	/// Initializes a new instance of the <see cref="SAPHR_UnidadesOrganizativasSpecification"/> class.
    	/// </summary>
    	/// <param name="initializeNavigationProperties">if set to <c>true</c> initialize navigation properties.</param>
    	public SAPHR_UnidadesOrganizativasSpecification(bool initializeNavigationProperties)
    	{
    		if(!initializeNavigationProperties)
    			return;
    
    		this.SAPHR_Empresas = new SAPHR_EmpresasSpecification();
    	}
    
        #region ISpecification Members
    
    	public Expression<Func<SAPHR_UnidadesOrganizativas, bool>> GetExpression()
    	{
    		Expression<Func<SAPHR_UnidadesOrganizativas, bool>> expression = x => true;
    	
    		if(!string.IsNullOrWhiteSpace(IdUniOrganizativa))  
    			expression = expression.And(x => x.IdUniOrganizativa.Equals(IdUniOrganizativa));
    			
    		if(!string.IsNullOrWhiteSpace(IdUniOrganizativaContains))  
    			expression = expression.And(x => x.IdUniOrganizativa.Contains(IdUniOrganizativaContains));
    			
    		if(!string.IsNullOrWhiteSpace(IdUniOrganizativaStartsWith))
    			expression = expression.And(x => x.IdUniOrganizativa.StartsWith(IdUniOrganizativaStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(IdUniOrganizativaEndsWith))
    			expression = expression.And(x => x.IdUniOrganizativa.EndsWith(IdUniOrganizativaEndsWith));
    
    		if(IdUniOrganizativaIN != null && IdUniOrganizativaIN.Count() > 0)
    			expression = expression.And(x => IdUniOrganizativaIN.Contains(x.IdUniOrganizativa));
    	
    		if(!string.IsNullOrWhiteSpace(Nombre))  
    			expression = expression.And(x => x.Nombre.Equals(Nombre));
    			
    		if(!string.IsNullOrWhiteSpace(NombreContains))  
    			expression = expression.And(x => x.Nombre.Contains(NombreContains));
    			
    		if(!string.IsNullOrWhiteSpace(NombreStartsWith))
    			expression = expression.And(x => x.Nombre.StartsWith(NombreStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(NombreEndsWith))
    			expression = expression.And(x => x.Nombre.EndsWith(NombreEndsWith));
    
    		if(NombreIN != null && NombreIN.Count() > 0)
    			expression = expression.And(x => NombreIN.Contains(x.Nombre));
    
    		if(Empresa.HasValue)
    			expression = expression.And(x => x.Empresa == Empresa.Value);
    
    		if(EmpresaIN != null && EmpresaIN.Count() > 0)
    			expression = expression.And(x => EmpresaIN.Contains(x.Empresa));
    
    		if(Baja.HasValue)
    			expression = expression.And(x => x.Baja == Baja.Value);
    
    		if(BajaIN != null && BajaIN.Count() > 0)
    			expression = expression.And(x => BajaIN.Contains(x.Baja));
    
    		if(FechaBaja.HasValue)
    			expression = expression.And(x => x.FechaBaja == FechaBaja.Value);
    
    		if(FechaBajaIN != null && FechaBajaIN.Count() > 0)
    			expression = expression.And(x => FechaBajaIN.Contains(x.FechaBaja));
    	
    		if(FechaBajaFrom.HasValue)
    			expression = expression.And(x => x.FechaBaja >= FechaBajaFrom.Value);
    			
    		if(FechaBajaTo.HasValue)
    			expression = expression.And(x => x.FechaBaja <= FechaBajaTo.Value);
    				
    
    		if(FechaBajaFromOrNull.HasValue)
                expression = expression.And(x => x.FechaBaja >= FechaBajaFromOrNull.Value || x.FechaBaja == null);
    
            if(FechaBajaToOrNull.HasValue)
                expression = expression.And(x => x.FechaBaja <= FechaBajaToOrNull.Value || x.FechaBaja == null);
    		
    		//
    		// Navigation properties
    		//
    
    		if(this.SAPHR_Empresas != null)
    		{
    			var subExpression = SAPHR_Empresas.GetExpression();
    			expression = expression.And(x => (new[] { x.SAPHR_Empresas }).AsQueryable().Any(subExpression));
    		}
    	
    		return expression;
    	}
    	
    	public bool IsSatisfiedBy(SAPHR_UnidadesOrganizativas entity)
    	{
    		// convert single entity to a IQueryable object, 
    		// in order to be able to use lambda expressions
    		IQueryable<SAPHR_UnidadesOrganizativas> entities = (new[] { entity }).AsQueryable();
    		
    		return entities.Any(this.GetExpression());
    	}
    
        public override string ToString()
        {
            return Evaluator.PartialEval(this.GetExpression()).ToString();
        }

        #endregion

    }
}
