//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;


using System.Collections.Generic;
using TK_ECAR.Domain.DomainModel;

namespace TK_ECAR.Domain.Specifications
{
    
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("GeneratedCode","1.0")]
    
    [Serializable]
    public partial class T_G_USUARIOS_EMPRESASSpecification : ISpecification<T_G_USUARIOS_EMPRESAS>
    {
    
        public Nullable<int> ID_USUARIO
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> ID_USUARIOIN
    	{
    		get;
    		set;
    	}
    
        public Nullable<int> ID_EMPRESA
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> ID_EMPRESAIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<int> ID_EMPRESAFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<int> ID_EMPRESATo
    	{
    		get;
    		set;
    	}
    	 
        
    
    
        #region Navigation Properties
    
    	public T_G_USUARIOSSpecification T_G_USUARIOS
        {
            get;
    		set;
    	}

        #endregion

    
    	/// <summary>
    	/// Default constructor (needed for serialization)
    	/// Initializes a new instance of the <see cref="T_G_USUARIOS_EMPRESASSpecification"/> class.
    	/// </summary>
    	public T_G_USUARIOS_EMPRESASSpecification()
    	{
    
    	}
    
    	/// <summary>
    	/// Initializes a new instance of the <see cref="T_G_USUARIOS_EMPRESASSpecification"/> class.
    	/// </summary>
    	/// <param name="initializeNavigationProperties">if set to <c>true</c> initialize navigation properties.</param>
    	public T_G_USUARIOS_EMPRESASSpecification(bool initializeNavigationProperties)
    	{
    		if(!initializeNavigationProperties)
    			return;
    
    		this.T_G_USUARIOS = new T_G_USUARIOSSpecification();
    	}
    
        #region ISpecification Members
    
    	public Expression<Func<T_G_USUARIOS_EMPRESAS, bool>> GetExpression()
    	{
    		Expression<Func<T_G_USUARIOS_EMPRESAS, bool>> expression = x => true;
    
    		if(ID_USUARIO.HasValue)
    			expression = expression.And(x => x.ID_USUARIO == ID_USUARIO.Value);
    
    		if(ID_USUARIOIN != null && ID_USUARIOIN.Count() > 0)
    			expression = expression.And(x => ID_USUARIOIN.Contains(x.ID_USUARIO));
    
    		if(ID_EMPRESA.HasValue)
    			expression = expression.And(x => x.ID_EMPRESA == ID_EMPRESA.Value);
    
    		if(ID_EMPRESAIN != null && ID_EMPRESAIN.Count() > 0)
    			expression = expression.And(x => ID_EMPRESAIN.Contains(x.ID_EMPRESA));
    	
    		if(ID_EMPRESAFrom.HasValue)
    			expression = expression.And(x => x.ID_EMPRESA >= ID_EMPRESAFrom.Value);
    			
    		if(ID_EMPRESATo.HasValue)
    			expression = expression.And(x => x.ID_EMPRESA <= ID_EMPRESATo.Value);
    				
    
    		
    		//
    		// Navigation properties
    		//
    
    		if(this.T_G_USUARIOS != null)
    		{
    			var subExpression = T_G_USUARIOS.GetExpression();
    			expression = expression.And(x => (new[] { x.T_G_USUARIOS }).AsQueryable().Any(subExpression));
    		}
    	
    		return expression;
    	}
    	
    	public bool IsSatisfiedBy(T_G_USUARIOS_EMPRESAS entity)
    	{
    		// convert single entity to a IQueryable object, 
    		// in order to be able to use lambda expressions
    		IQueryable<T_G_USUARIOS_EMPRESAS> entities = (new[] { entity }).AsQueryable();
    		
    		return entities.Any(this.GetExpression());
    	}
    
        public override string ToString()
        {
            return Evaluator.PartialEval(this.GetExpression()).ToString();
        }

        #endregion

    }
}
