//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;


using System.Collections.Generic;
using TK_ECAR.Domain.DomainModel;

namespace TK_ECAR.Domain.Specifications
{
    
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("GeneratedCode","1.0")]
    
    [Serializable]
    public partial class T_G_ALERTAS_OTRAS_NOTIFICACIONESSpecification : ISpecification<T_G_ALERTAS_OTRAS_NOTIFICACIONES>
    {
    
        public Nullable<int> ID_ALERTA
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> ID_ALERTAIN
    	{
    		get;
    		set;
    	}
    
        public Nullable<int> ID_TIPO_CLASIFICACION
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> ID_TIPO_CLASIFICACIONIN
    	{
    		get;
    		set;
    	}
    
        public string FICHERO
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> FICHEROIN
    	{
    		get;
    		set;
    	}
    
    	public string FICHEROContains
    	{
    		get;
    		set;
    	}
    	
    	public string FICHEROStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string FICHEROEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public string OBSERVACIONES
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> OBSERVACIONESIN
    	{
    		get;
    		set;
    	}
    
    	public string OBSERVACIONESContains
    	{
    		get;
    		set;
    	}
    	
    	public string OBSERVACIONESStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string OBSERVACIONESEndsWith
    	{
    		get;
    		set;
    	}
    
    
        #region Navigation Properties
    
    	public T_G_ALERTASSpecification T_G_ALERTAS
        {
            get;
    		set;
    	}
    
    	public T_M_TIPOS_CLASIFICACIONSpecification T_M_TIPOS_CLASIFICACION
        {
            get;
    		set;
    	}

        #endregion

    
    	/// <summary>
    	/// Default constructor (needed for serialization)
    	/// Initializes a new instance of the <see cref="T_G_ALERTAS_OTRAS_NOTIFICACIONESSpecification"/> class.
    	/// </summary>
    	public T_G_ALERTAS_OTRAS_NOTIFICACIONESSpecification()
    	{
    
    	}
    
    	/// <summary>
    	/// Initializes a new instance of the <see cref="T_G_ALERTAS_OTRAS_NOTIFICACIONESSpecification"/> class.
    	/// </summary>
    	/// <param name="initializeNavigationProperties">if set to <c>true</c> initialize navigation properties.</param>
    	public T_G_ALERTAS_OTRAS_NOTIFICACIONESSpecification(bool initializeNavigationProperties)
    	{
    		if(!initializeNavigationProperties)
    			return;
    
    		this.T_G_ALERTAS = new T_G_ALERTASSpecification();
    		this.T_M_TIPOS_CLASIFICACION = new T_M_TIPOS_CLASIFICACIONSpecification();
    	}
    
        #region ISpecification Members
    
    	public Expression<Func<T_G_ALERTAS_OTRAS_NOTIFICACIONES, bool>> GetExpression()
    	{
    		Expression<Func<T_G_ALERTAS_OTRAS_NOTIFICACIONES, bool>> expression = x => true;
    
    		if(ID_ALERTA.HasValue)
    			expression = expression.And(x => x.ID_ALERTA == ID_ALERTA.Value);
    
    		if(ID_ALERTAIN != null && ID_ALERTAIN.Count() > 0)
    			expression = expression.And(x => ID_ALERTAIN.Contains(x.ID_ALERTA));
    
    		if(ID_TIPO_CLASIFICACION.HasValue)
    			expression = expression.And(x => x.ID_TIPO_CLASIFICACION == ID_TIPO_CLASIFICACION.Value);
    
    		if(ID_TIPO_CLASIFICACIONIN != null && ID_TIPO_CLASIFICACIONIN.Count() > 0)
    			expression = expression.And(x => ID_TIPO_CLASIFICACIONIN.Contains(x.ID_TIPO_CLASIFICACION));
    	
    		if(!string.IsNullOrWhiteSpace(FICHERO))  
    			expression = expression.And(x => x.FICHERO.Equals(FICHERO));
    			
    		if(!string.IsNullOrWhiteSpace(FICHEROContains))  
    			expression = expression.And(x => x.FICHERO.Contains(FICHEROContains));
    			
    		if(!string.IsNullOrWhiteSpace(FICHEROStartsWith))
    			expression = expression.And(x => x.FICHERO.StartsWith(FICHEROStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(FICHEROEndsWith))
    			expression = expression.And(x => x.FICHERO.EndsWith(FICHEROEndsWith));
    
    		if(FICHEROIN != null && FICHEROIN.Count() > 0)
    			expression = expression.And(x => FICHEROIN.Contains(x.FICHERO));
    	
    		if(!string.IsNullOrWhiteSpace(OBSERVACIONES))  
    			expression = expression.And(x => x.OBSERVACIONES.Equals(OBSERVACIONES));
    			
    		if(!string.IsNullOrWhiteSpace(OBSERVACIONESContains))  
    			expression = expression.And(x => x.OBSERVACIONES.Contains(OBSERVACIONESContains));
    			
    		if(!string.IsNullOrWhiteSpace(OBSERVACIONESStartsWith))
    			expression = expression.And(x => x.OBSERVACIONES.StartsWith(OBSERVACIONESStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(OBSERVACIONESEndsWith))
    			expression = expression.And(x => x.OBSERVACIONES.EndsWith(OBSERVACIONESEndsWith));
    
    		if(OBSERVACIONESIN != null && OBSERVACIONESIN.Count() > 0)
    			expression = expression.And(x => OBSERVACIONESIN.Contains(x.OBSERVACIONES));
    		
    		//
    		// Navigation properties
    		//
    
    		if(this.T_G_ALERTAS != null)
    		{
    			var subExpression = T_G_ALERTAS.GetExpression();
    			expression = expression.And(x => (new[] { x.T_G_ALERTAS }).AsQueryable().Any(subExpression));
    		}
    
    		if(this.T_M_TIPOS_CLASIFICACION != null)
    		{
    			var subExpression = T_M_TIPOS_CLASIFICACION.GetExpression();
    			expression = expression.And(x => (new[] { x.T_M_TIPOS_CLASIFICACION }).AsQueryable().Any(subExpression));
    		}
    	
    		return expression;
    	}
    	
    	public bool IsSatisfiedBy(T_G_ALERTAS_OTRAS_NOTIFICACIONES entity)
    	{
    		// convert single entity to a IQueryable object, 
    		// in order to be able to use lambda expressions
    		IQueryable<T_G_ALERTAS_OTRAS_NOTIFICACIONES> entities = (new[] { entity }).AsQueryable();
    		
    		return entities.Any(this.GetExpression());
    	}
    
        public override string ToString()
        {
            return Evaluator.PartialEval(this.GetExpression()).ToString();
        }

        #endregion

    }
}
