//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;


using System.Collections.Generic;
using TK_ECAR.Domain.DomainModel;

namespace TK_ECAR.Domain.Specifications
{
    
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("GeneratedCode","1.0")]
    
    [Serializable]
    public partial class T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTORSpecification : ISpecification<T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTOR>
    {
    
        public Nullable<int> ID_ALERTA
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> ID_ALERTAIN
    	{
    		get;
    		set;
    	}
    
        public Nullable<int> COD_CONDUCTOR
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> COD_CONDUCTORIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<int> COD_CONDUCTORFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<int> COD_CONDUCTORTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    
        public string DNI
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> DNIIN
    	{
    		get;
    		set;
    	}
    
    	public string DNIContains
    	{
    		get;
    		set;
    	}
    	
    	public string DNIStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string DNIEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public string NOMBRE
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> NOMBREIN
    	{
    		get;
    		set;
    	}
    
    	public string NOMBREContains
    	{
    		get;
    		set;
    	}
    	
    	public string NOMBREStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string NOMBREEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public string DIRECCION
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> DIRECCIONIN
    	{
    		get;
    		set;
    	}
    
    	public string DIRECCIONContains
    	{
    		get;
    		set;
    	}
    	
    	public string DIRECCIONStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string DIRECCIONEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public string CP
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> CPIN
    	{
    		get;
    		set;
    	}
    
    	public string CPContains
    	{
    		get;
    		set;
    	}
    	
    	public string CPStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string CPEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public string PROVINCIA
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> PROVINCIAIN
    	{
    		get;
    		set;
    	}
    
    	public string PROVINCIAContains
    	{
    		get;
    		set;
    	}
    	
    	public string PROVINCIAStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string PROVINCIAEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public string POBLACION
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> POBLACIONIN
    	{
    		get;
    		set;
    	}
    
    	public string POBLACIONContains
    	{
    		get;
    		set;
    	}
    	
    	public string POBLACIONStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string POBLACIONEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public Nullable<System.DateTime> FECHA_NACIMIENTO
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<System.DateTime>> FECHA_NACIMIENTOIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<System.DateTime> FECHA_NACIMIENTOFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<System.DateTime> FECHA_NACIMIENTOTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    	public Nullable<System.DateTime> FECHA_NACIMIENTOFromOrNull
        {
            get;
            set;
        }
    
                    
        public Nullable<System.DateTime> FECHA_NACIMIENTOToOrNull
        {
            get;
            set;
        }
    		
    
        public Nullable<System.DateTime> FECHA_VENCIMIENTO_CARNET
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<System.DateTime>> FECHA_VENCIMIENTO_CARNETIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<System.DateTime> FECHA_VENCIMIENTO_CARNETFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<System.DateTime> FECHA_VENCIMIENTO_CARNETTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    	public Nullable<System.DateTime> FECHA_VENCIMIENTO_CARNETFromOrNull
        {
            get;
            set;
        }
    
                    
        public Nullable<System.DateTime> FECHA_VENCIMIENTO_CARNETToOrNull
        {
            get;
            set;
        }
    		
    
        #region Navigation Properties
    
    	public T_G_ALERTASSpecification T_G_ALERTAS
        {
            get;
    		set;
    	}

        #endregion

    
    	/// <summary>
    	/// Default constructor (needed for serialization)
    	/// Initializes a new instance of the <see cref="T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTORSpecification"/> class.
    	/// </summary>
    	public T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTORSpecification()
    	{
    
    	}
    
    	/// <summary>
    	/// Initializes a new instance of the <see cref="T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTORSpecification"/> class.
    	/// </summary>
    	/// <param name="initializeNavigationProperties">if set to <c>true</c> initialize navigation properties.</param>
    	public T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTORSpecification(bool initializeNavigationProperties)
    	{
    		if(!initializeNavigationProperties)
    			return;
    
    		this.T_G_ALERTAS = new T_G_ALERTASSpecification();
    	}
    
        #region ISpecification Members
    
    	public Expression<Func<T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTOR, bool>> GetExpression()
    	{
    		Expression<Func<T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTOR, bool>> expression = x => true;
    
    		if(ID_ALERTA.HasValue)
    			expression = expression.And(x => x.ID_ALERTA == ID_ALERTA.Value);
    
    		if(ID_ALERTAIN != null && ID_ALERTAIN.Count() > 0)
    			expression = expression.And(x => ID_ALERTAIN.Contains(x.ID_ALERTA));
    
    		if(COD_CONDUCTOR.HasValue)
    			expression = expression.And(x => x.COD_CONDUCTOR == COD_CONDUCTOR.Value);
    
    		if(COD_CONDUCTORIN != null && COD_CONDUCTORIN.Count() > 0)
    			expression = expression.And(x => COD_CONDUCTORIN.Contains(x.COD_CONDUCTOR));
    	
    		if(COD_CONDUCTORFrom.HasValue)
    			expression = expression.And(x => x.COD_CONDUCTOR >= COD_CONDUCTORFrom.Value);
    			
    		if(COD_CONDUCTORTo.HasValue)
    			expression = expression.And(x => x.COD_CONDUCTOR <= COD_CONDUCTORTo.Value);
    				
    
    	
    		if(!string.IsNullOrWhiteSpace(DNI))  
    			expression = expression.And(x => x.DNI.Equals(DNI));
    			
    		if(!string.IsNullOrWhiteSpace(DNIContains))  
    			expression = expression.And(x => x.DNI.Contains(DNIContains));
    			
    		if(!string.IsNullOrWhiteSpace(DNIStartsWith))
    			expression = expression.And(x => x.DNI.StartsWith(DNIStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(DNIEndsWith))
    			expression = expression.And(x => x.DNI.EndsWith(DNIEndsWith));
    
    		if(DNIIN != null && DNIIN.Count() > 0)
    			expression = expression.And(x => DNIIN.Contains(x.DNI));
    	
    		if(!string.IsNullOrWhiteSpace(NOMBRE))  
    			expression = expression.And(x => x.NOMBRE.Equals(NOMBRE));
    			
    		if(!string.IsNullOrWhiteSpace(NOMBREContains))  
    			expression = expression.And(x => x.NOMBRE.Contains(NOMBREContains));
    			
    		if(!string.IsNullOrWhiteSpace(NOMBREStartsWith))
    			expression = expression.And(x => x.NOMBRE.StartsWith(NOMBREStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(NOMBREEndsWith))
    			expression = expression.And(x => x.NOMBRE.EndsWith(NOMBREEndsWith));
    
    		if(NOMBREIN != null && NOMBREIN.Count() > 0)
    			expression = expression.And(x => NOMBREIN.Contains(x.NOMBRE));
    	
    		if(!string.IsNullOrWhiteSpace(DIRECCION))  
    			expression = expression.And(x => x.DIRECCION.Equals(DIRECCION));
    			
    		if(!string.IsNullOrWhiteSpace(DIRECCIONContains))  
    			expression = expression.And(x => x.DIRECCION.Contains(DIRECCIONContains));
    			
    		if(!string.IsNullOrWhiteSpace(DIRECCIONStartsWith))
    			expression = expression.And(x => x.DIRECCION.StartsWith(DIRECCIONStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(DIRECCIONEndsWith))
    			expression = expression.And(x => x.DIRECCION.EndsWith(DIRECCIONEndsWith));
    
    		if(DIRECCIONIN != null && DIRECCIONIN.Count() > 0)
    			expression = expression.And(x => DIRECCIONIN.Contains(x.DIRECCION));
    	
    		if(!string.IsNullOrWhiteSpace(CP))  
    			expression = expression.And(x => x.CP.Equals(CP));
    			
    		if(!string.IsNullOrWhiteSpace(CPContains))  
    			expression = expression.And(x => x.CP.Contains(CPContains));
    			
    		if(!string.IsNullOrWhiteSpace(CPStartsWith))
    			expression = expression.And(x => x.CP.StartsWith(CPStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(CPEndsWith))
    			expression = expression.And(x => x.CP.EndsWith(CPEndsWith));
    
    		if(CPIN != null && CPIN.Count() > 0)
    			expression = expression.And(x => CPIN.Contains(x.CP));
    	
    		if(!string.IsNullOrWhiteSpace(PROVINCIA))  
    			expression = expression.And(x => x.PROVINCIA.Equals(PROVINCIA));
    			
    		if(!string.IsNullOrWhiteSpace(PROVINCIAContains))  
    			expression = expression.And(x => x.PROVINCIA.Contains(PROVINCIAContains));
    			
    		if(!string.IsNullOrWhiteSpace(PROVINCIAStartsWith))
    			expression = expression.And(x => x.PROVINCIA.StartsWith(PROVINCIAStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(PROVINCIAEndsWith))
    			expression = expression.And(x => x.PROVINCIA.EndsWith(PROVINCIAEndsWith));
    
    		if(PROVINCIAIN != null && PROVINCIAIN.Count() > 0)
    			expression = expression.And(x => PROVINCIAIN.Contains(x.PROVINCIA));
    	
    		if(!string.IsNullOrWhiteSpace(POBLACION))  
    			expression = expression.And(x => x.POBLACION.Equals(POBLACION));
    			
    		if(!string.IsNullOrWhiteSpace(POBLACIONContains))  
    			expression = expression.And(x => x.POBLACION.Contains(POBLACIONContains));
    			
    		if(!string.IsNullOrWhiteSpace(POBLACIONStartsWith))
    			expression = expression.And(x => x.POBLACION.StartsWith(POBLACIONStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(POBLACIONEndsWith))
    			expression = expression.And(x => x.POBLACION.EndsWith(POBLACIONEndsWith));
    
    		if(POBLACIONIN != null && POBLACIONIN.Count() > 0)
    			expression = expression.And(x => POBLACIONIN.Contains(x.POBLACION));
    
    		if(FECHA_NACIMIENTO.HasValue)
    			expression = expression.And(x => x.FECHA_NACIMIENTO == FECHA_NACIMIENTO.Value);
    
    		if(FECHA_NACIMIENTOIN != null && FECHA_NACIMIENTOIN.Count() > 0)
    			expression = expression.And(x => FECHA_NACIMIENTOIN.Contains(x.FECHA_NACIMIENTO));
    	
    		if(FECHA_NACIMIENTOFrom.HasValue)
    			expression = expression.And(x => x.FECHA_NACIMIENTO >= FECHA_NACIMIENTOFrom.Value);
    			
    		if(FECHA_NACIMIENTOTo.HasValue)
    			expression = expression.And(x => x.FECHA_NACIMIENTO <= FECHA_NACIMIENTOTo.Value);
    				
    
    		if(FECHA_NACIMIENTOFromOrNull.HasValue)
                expression = expression.And(x => x.FECHA_NACIMIENTO >= FECHA_NACIMIENTOFromOrNull.Value || x.FECHA_NACIMIENTO == null);
    
            if(FECHA_NACIMIENTOToOrNull.HasValue)
                expression = expression.And(x => x.FECHA_NACIMIENTO <= FECHA_NACIMIENTOToOrNull.Value || x.FECHA_NACIMIENTO == null);
    
    		if(FECHA_VENCIMIENTO_CARNET.HasValue)
    			expression = expression.And(x => x.FECHA_VENCIMIENTO_CARNET == FECHA_VENCIMIENTO_CARNET.Value);
    
    		if(FECHA_VENCIMIENTO_CARNETIN != null && FECHA_VENCIMIENTO_CARNETIN.Count() > 0)
    			expression = expression.And(x => FECHA_VENCIMIENTO_CARNETIN.Contains(x.FECHA_VENCIMIENTO_CARNET));
    	
    		if(FECHA_VENCIMIENTO_CARNETFrom.HasValue)
    			expression = expression.And(x => x.FECHA_VENCIMIENTO_CARNET >= FECHA_VENCIMIENTO_CARNETFrom.Value);
    			
    		if(FECHA_VENCIMIENTO_CARNETTo.HasValue)
    			expression = expression.And(x => x.FECHA_VENCIMIENTO_CARNET <= FECHA_VENCIMIENTO_CARNETTo.Value);
    				
    
    		if(FECHA_VENCIMIENTO_CARNETFromOrNull.HasValue)
                expression = expression.And(x => x.FECHA_VENCIMIENTO_CARNET >= FECHA_VENCIMIENTO_CARNETFromOrNull.Value || x.FECHA_VENCIMIENTO_CARNET == null);
    
            if(FECHA_VENCIMIENTO_CARNETToOrNull.HasValue)
                expression = expression.And(x => x.FECHA_VENCIMIENTO_CARNET <= FECHA_VENCIMIENTO_CARNETToOrNull.Value || x.FECHA_VENCIMIENTO_CARNET == null);
    		
    		//
    		// Navigation properties
    		//
    
    		if(this.T_G_ALERTAS != null)
    		{
    			var subExpression = T_G_ALERTAS.GetExpression();
    			expression = expression.And(x => (new[] { x.T_G_ALERTAS }).AsQueryable().Any(subExpression));
    		}
    	
    		return expression;
    	}
    	
    	public bool IsSatisfiedBy(T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTOR entity)
    	{
    		// convert single entity to a IQueryable object, 
    		// in order to be able to use lambda expressions
    		IQueryable<T_G_ALERTAS_RENTING_CONFIRMACION_CONDUCTOR> entities = (new[] { entity }).AsQueryable();
    		
    		return entities.Any(this.GetExpression());
    	}
    
        public override string ToString()
        {
            return Evaluator.PartialEval(this.GetExpression()).ToString();
        }

        #endregion

    }
}
