//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;


using System.Collections.Generic;
using TK_ECAR.Domain.DomainModel;

namespace TK_ECAR.Domain.Specifications
{
    
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("GeneratedCode","1.0")]
    
    [Serializable]
    public partial class T_M_TIPOS_VEHICULOSpecification : ISpecification<T_M_TIPOS_VEHICULO>
    {
    
        public Nullable<int> ID_TIPO_VEHICULO
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> ID_TIPO_VEHICULOIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<int> ID_TIPO_VEHICULOFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<int> ID_TIPO_VEHICULOTo
    	{
    		get;
    		set;
    	}
    	 
        
    
    
        public string DESCRIPCION
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> DESCRIPCIONIN
    	{
    		get;
    		set;
    	}
    
    	public string DESCRIPCIONContains
    	{
    		get;
    		set;
    	}
    	
    	public string DESCRIPCIONStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string DESCRIPCIONEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public Nullable<bool> BAJA
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<bool>> BAJAIN
    	{
    		get;
    		set;
    	}
    
        public Nullable<bool> TIENE_ITV
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<bool>> TIENE_ITVIN
    	{
    		get;
    		set;
    	}
    
        #region Navigation Properties
    
    	public ECAR_Datos_VehiculoSpecification ECAR_Datos_Vehiculo
        {
            get;
    		set;
    	}

        #endregion

    
    	/// <summary>
    	/// Default constructor (needed for serialization)
    	/// Initializes a new instance of the <see cref="T_M_TIPOS_VEHICULOSpecification"/> class.
    	/// </summary>
    	public T_M_TIPOS_VEHICULOSpecification()
    	{
    
    	}
    
    	/// <summary>
    	/// Initializes a new instance of the <see cref="T_M_TIPOS_VEHICULOSpecification"/> class.
    	/// </summary>
    	/// <param name="initializeNavigationProperties">if set to <c>true</c> initialize navigation properties.</param>
    	public T_M_TIPOS_VEHICULOSpecification(bool initializeNavigationProperties)
    	{
    		if(!initializeNavigationProperties)
    			return;
    
    		this.ECAR_Datos_Vehiculo = new ECAR_Datos_VehiculoSpecification();
    	}
    
        #region ISpecification Members
    
    	public Expression<Func<T_M_TIPOS_VEHICULO, bool>> GetExpression()
    	{
    		Expression<Func<T_M_TIPOS_VEHICULO, bool>> expression = x => true;
    
    		if(ID_TIPO_VEHICULO.HasValue)
    			expression = expression.And(x => x.ID_TIPO_VEHICULO == ID_TIPO_VEHICULO.Value);
    
    		if(ID_TIPO_VEHICULOIN != null && ID_TIPO_VEHICULOIN.Count() > 0)
    			expression = expression.And(x => ID_TIPO_VEHICULOIN.Contains(x.ID_TIPO_VEHICULO));
    	
    		if(ID_TIPO_VEHICULOFrom.HasValue)
    			expression = expression.And(x => x.ID_TIPO_VEHICULO >= ID_TIPO_VEHICULOFrom.Value);
    			
    		if(ID_TIPO_VEHICULOTo.HasValue)
    			expression = expression.And(x => x.ID_TIPO_VEHICULO <= ID_TIPO_VEHICULOTo.Value);
    				
    
    	
    		if(!string.IsNullOrWhiteSpace(DESCRIPCION))  
    			expression = expression.And(x => x.DESCRIPCION.Equals(DESCRIPCION));
    			
    		if(!string.IsNullOrWhiteSpace(DESCRIPCIONContains))  
    			expression = expression.And(x => x.DESCRIPCION.Contains(DESCRIPCIONContains));
    			
    		if(!string.IsNullOrWhiteSpace(DESCRIPCIONStartsWith))
    			expression = expression.And(x => x.DESCRIPCION.StartsWith(DESCRIPCIONStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(DESCRIPCIONEndsWith))
    			expression = expression.And(x => x.DESCRIPCION.EndsWith(DESCRIPCIONEndsWith));
    
    		if(DESCRIPCIONIN != null && DESCRIPCIONIN.Count() > 0)
    			expression = expression.And(x => DESCRIPCIONIN.Contains(x.DESCRIPCION));
    
    		if(BAJA.HasValue)
    			expression = expression.And(x => x.BAJA == BAJA.Value);
    
    		if(BAJAIN != null && BAJAIN.Count() > 0)
    			expression = expression.And(x => BAJAIN.Contains(x.BAJA));
    
    		if(TIENE_ITV.HasValue)
    			expression = expression.And(x => x.TIENE_ITV == TIENE_ITV.Value);
    
    		if(TIENE_ITVIN != null && TIENE_ITVIN.Count() > 0)
    			expression = expression.And(x => TIENE_ITVIN.Contains(x.TIENE_ITV));
    		
    		//
    		// Navigation properties
    		//
    
    		if(this.ECAR_Datos_Vehiculo != null)
    		{
    			var subExpression = ECAR_Datos_Vehiculo.GetExpression();
    			expression = expression.And(x => x.ECAR_Datos_Vehiculo.AsQueryable().Any(subExpression));
    		}
    	
    		return expression;
    	}
    	
    	public bool IsSatisfiedBy(T_M_TIPOS_VEHICULO entity)
    	{
    		// convert single entity to a IQueryable object, 
    		// in order to be able to use lambda expressions
    		IQueryable<T_M_TIPOS_VEHICULO> entities = (new[] { entity }).AsQueryable();
    		
    		return entities.Any(this.GetExpression());
    	}
    
        public override string ToString()
        {
            return Evaluator.PartialEval(this.GetExpression()).ToString();
        }

        #endregion

    }
}
