//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;


using System.Collections.Generic;
using TK_ECAR.Domain.DomainModel;

namespace TK_ECAR.Domain.Specifications
{
    
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("GeneratedCode","1.0")]
    
    [Serializable]
    public partial class T_M_MARCA_VEHICULOSSpecification : ISpecification<T_M_MARCA_VEHICULOS>
    {
    
        public Nullable<int> ID_MARCA
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> ID_MARCAIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<int> ID_MARCAFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<int> ID_MARCATo
    	{
    		get;
    		set;
    	}
    	 
        
    
    
        public string DESCRIPCION
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> DESCRIPCIONIN
    	{
    		get;
    		set;
    	}
    
    	public string DESCRIPCIONContains
    	{
    		get;
    		set;
    	}
    	
    	public string DESCRIPCIONStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string DESCRIPCIONEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public Nullable<bool> BAJA
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<bool>> BAJAIN
    	{
    		get;
    		set;
    	}
    
        #region Navigation Properties
    
    	public T_M_MODELOS_VEHICULOSpecification T_M_MODELOS_VEHICULO
        {
            get;
    		set;
    	}
    
    	public ECAR_Datos_VehiculoSpecification ECAR_Datos_Vehiculo
        {
            get;
    		set;
    	}

        #endregion

    
    	/// <summary>
    	/// Default constructor (needed for serialization)
    	/// Initializes a new instance of the <see cref="T_M_MARCA_VEHICULOSSpecification"/> class.
    	/// </summary>
    	public T_M_MARCA_VEHICULOSSpecification()
    	{
    
    	}
    
    	/// <summary>
    	/// Initializes a new instance of the <see cref="T_M_MARCA_VEHICULOSSpecification"/> class.
    	/// </summary>
    	/// <param name="initializeNavigationProperties">if set to <c>true</c> initialize navigation properties.</param>
    	public T_M_MARCA_VEHICULOSSpecification(bool initializeNavigationProperties)
    	{
    		if(!initializeNavigationProperties)
    			return;
    
    		this.T_M_MODELOS_VEHICULO = new T_M_MODELOS_VEHICULOSpecification();
    		this.ECAR_Datos_Vehiculo = new ECAR_Datos_VehiculoSpecification();
    	}
    
        #region ISpecification Members
    
    	public Expression<Func<T_M_MARCA_VEHICULOS, bool>> GetExpression()
    	{
    		Expression<Func<T_M_MARCA_VEHICULOS, bool>> expression = x => true;
    
    		if(ID_MARCA.HasValue)
    			expression = expression.And(x => x.ID_MARCA == ID_MARCA.Value);
    
    		if(ID_MARCAIN != null && ID_MARCAIN.Count() > 0)
    			expression = expression.And(x => ID_MARCAIN.Contains(x.ID_MARCA));
    	
    		if(ID_MARCAFrom.HasValue)
    			expression = expression.And(x => x.ID_MARCA >= ID_MARCAFrom.Value);
    			
    		if(ID_MARCATo.HasValue)
    			expression = expression.And(x => x.ID_MARCA <= ID_MARCATo.Value);
    				
    
    	
    		if(!string.IsNullOrWhiteSpace(DESCRIPCION))  
    			expression = expression.And(x => x.DESCRIPCION.Equals(DESCRIPCION));
    			
    		if(!string.IsNullOrWhiteSpace(DESCRIPCIONContains))  
    			expression = expression.And(x => x.DESCRIPCION.Contains(DESCRIPCIONContains));
    			
    		if(!string.IsNullOrWhiteSpace(DESCRIPCIONStartsWith))
    			expression = expression.And(x => x.DESCRIPCION.StartsWith(DESCRIPCIONStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(DESCRIPCIONEndsWith))
    			expression = expression.And(x => x.DESCRIPCION.EndsWith(DESCRIPCIONEndsWith));
    
    		if(DESCRIPCIONIN != null && DESCRIPCIONIN.Count() > 0)
    			expression = expression.And(x => DESCRIPCIONIN.Contains(x.DESCRIPCION));
    
    		if(BAJA.HasValue)
    			expression = expression.And(x => x.BAJA == BAJA.Value);
    
    		if(BAJAIN != null && BAJAIN.Count() > 0)
    			expression = expression.And(x => BAJAIN.Contains(x.BAJA));
    		
    		//
    		// Navigation properties
    		//
    
    		if(this.T_M_MODELOS_VEHICULO != null)
    		{
    			var subExpression = T_M_MODELOS_VEHICULO.GetExpression();
    			expression = expression.And(x => x.T_M_MODELOS_VEHICULO.AsQueryable().Any(subExpression));
    		}
    
    		if(this.ECAR_Datos_Vehiculo != null)
    		{
    			var subExpression = ECAR_Datos_Vehiculo.GetExpression();
    			expression = expression.And(x => x.ECAR_Datos_Vehiculo.AsQueryable().Any(subExpression));
    		}
    	
    		return expression;
    	}
    	
    	public bool IsSatisfiedBy(T_M_MARCA_VEHICULOS entity)
    	{
    		// convert single entity to a IQueryable object, 
    		// in order to be able to use lambda expressions
    		IQueryable<T_M_MARCA_VEHICULOS> entities = (new[] { entity }).AsQueryable();
    		
    		return entities.Any(this.GetExpression());
    	}
    
        public override string ToString()
        {
            return Evaluator.PartialEval(this.GetExpression()).ToString();
        }

        #endregion

    }
}
