//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;


using System.Collections.Generic;
using TK_ECAR.Domain.DomainModel;

namespace TK_ECAR.Domain.Specifications
{
    
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("GeneratedCode","1.0")]
    
    [Serializable]
    public partial class T_M_TIPOS_COSTESpecification : ISpecification<T_M_TIPOS_COSTE>
    {
    
        public Nullable<int> ID_TIPOCOSTE
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> ID_TIPOCOSTEIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<int> ID_TIPOCOSTEFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<int> ID_TIPOCOSTETo
    	{
    		get;
    		set;
    	}
    	 
        
    
    
        public string DESCRIPCION
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> DESCRIPCIONIN
    	{
    		get;
    		set;
    	}
    
    	public string DESCRIPCIONContains
    	{
    		get;
    		set;
    	}
    	
    	public string DESCRIPCIONStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string DESCRIPCIONEndsWith
    	{
    		get;
    		set;
    	}
    
    
        #region Navigation Properties
    
    	public T_R_TIPOSCOSTE_CUENTA_CONTABLESpecification T_R_TIPOSCOSTE_CUENTA_CONTABLE
        {
            get;
    		set;
    	}

        #endregion

    
    	/// <summary>
    	/// Default constructor (needed for serialization)
    	/// Initializes a new instance of the <see cref="T_M_TIPOS_COSTESpecification"/> class.
    	/// </summary>
    	public T_M_TIPOS_COSTESpecification()
    	{
    
    	}
    
    	/// <summary>
    	/// Initializes a new instance of the <see cref="T_M_TIPOS_COSTESpecification"/> class.
    	/// </summary>
    	/// <param name="initializeNavigationProperties">if set to <c>true</c> initialize navigation properties.</param>
    	public T_M_TIPOS_COSTESpecification(bool initializeNavigationProperties)
    	{
    		if(!initializeNavigationProperties)
    			return;
    
    		this.T_R_TIPOSCOSTE_CUENTA_CONTABLE = new T_R_TIPOSCOSTE_CUENTA_CONTABLESpecification();
    	}
    
        #region ISpecification Members
    
    	public Expression<Func<T_M_TIPOS_COSTE, bool>> GetExpression()
    	{
    		Expression<Func<T_M_TIPOS_COSTE, bool>> expression = x => true;
    
    		if(ID_TIPOCOSTE.HasValue)
    			expression = expression.And(x => x.ID_TIPOCOSTE == ID_TIPOCOSTE.Value);
    
    		if(ID_TIPOCOSTEIN != null && ID_TIPOCOSTEIN.Count() > 0)
    			expression = expression.And(x => ID_TIPOCOSTEIN.Contains(x.ID_TIPOCOSTE));
    	
    		if(ID_TIPOCOSTEFrom.HasValue)
    			expression = expression.And(x => x.ID_TIPOCOSTE >= ID_TIPOCOSTEFrom.Value);
    			
    		if(ID_TIPOCOSTETo.HasValue)
    			expression = expression.And(x => x.ID_TIPOCOSTE <= ID_TIPOCOSTETo.Value);
    				
    
    	
    		if(!string.IsNullOrWhiteSpace(DESCRIPCION))  
    			expression = expression.And(x => x.DESCRIPCION.Equals(DESCRIPCION));
    			
    		if(!string.IsNullOrWhiteSpace(DESCRIPCIONContains))  
    			expression = expression.And(x => x.DESCRIPCION.Contains(DESCRIPCIONContains));
    			
    		if(!string.IsNullOrWhiteSpace(DESCRIPCIONStartsWith))
    			expression = expression.And(x => x.DESCRIPCION.StartsWith(DESCRIPCIONStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(DESCRIPCIONEndsWith))
    			expression = expression.And(x => x.DESCRIPCION.EndsWith(DESCRIPCIONEndsWith));
    
    		if(DESCRIPCIONIN != null && DESCRIPCIONIN.Count() > 0)
    			expression = expression.And(x => DESCRIPCIONIN.Contains(x.DESCRIPCION));
    		
    		//
    		// Navigation properties
    		//
    
    		if(this.T_R_TIPOSCOSTE_CUENTA_CONTABLE != null)
    		{
    			var subExpression = T_R_TIPOSCOSTE_CUENTA_CONTABLE.GetExpression();
    			expression = expression.And(x => x.T_R_TIPOSCOSTE_CUENTA_CONTABLE.AsQueryable().Any(subExpression));
    		}
    	
    		return expression;
    	}
    	
    	public bool IsSatisfiedBy(T_M_TIPOS_COSTE entity)
    	{
    		// convert single entity to a IQueryable object, 
    		// in order to be able to use lambda expressions
    		IQueryable<T_M_TIPOS_COSTE> entities = (new[] { entity }).AsQueryable();
    		
    		return entities.Any(this.GetExpression());
    	}
    
        public override string ToString()
        {
            return Evaluator.PartialEval(this.GetExpression()).ToString();
        }

        #endregion

    }
}
