//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;


using System.Collections.Generic;
using TK_ECAR.Domain.DomainModel;

namespace TK_ECAR.Domain.Specifications
{
    
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("GeneratedCode","1.0")]
    
    [Serializable]
    public partial class T_M_TIPO_TARJETA_COMBUSTIBLESpecification : ISpecification<T_M_TIPO_TARJETA_COMBUSTIBLE>
    {
    
        public Nullable<int> ID_TARJETA_COMBUSTIBLE
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<int>> ID_TARJETA_COMBUSTIBLEIN
    	{
    		get;
    		set;
    	}
    
    	public Nullable<int> ID_TARJETA_COMBUSTIBLEFrom
    	{
    		get;
    		set;
    	}
    	
    	public Nullable<int> ID_TARJETA_COMBUSTIBLETo
    	{
    		get;
    		set;
    	}
    	 
        
    
    
        public string DESCRIPCION
        {
            get; 
            set;
        }
    		
    	public IEnumerable<string> DESCRIPCIONIN
    	{
    		get;
    		set;
    	}
    
    	public string DESCRIPCIONContains
    	{
    		get;
    		set;
    	}
    	
    	public string DESCRIPCIONStartsWith
    	{
    		get;
    		set;
    	}
    	
    	public string DESCRIPCIONEndsWith
    	{
    		get;
    		set;
    	}
    
    
        public Nullable<bool> BAJA
        {
            get; 
            set;
        }
    		
    	public IEnumerable<Nullable<bool>> BAJAIN
    	{
    		get;
    		set;
    	}
    
        #region Navigation Properties
    
    	public T_M_TARJETAS_CONBUSTIBLESpecification T_M_TARJETAS_CONBUSTIBLE
        {
            get;
    		set;
    	}

        #endregion

    
    	/// <summary>
    	/// Default constructor (needed for serialization)
    	/// Initializes a new instance of the <see cref="T_M_TIPO_TARJETA_COMBUSTIBLESpecification"/> class.
    	/// </summary>
    	public T_M_TIPO_TARJETA_COMBUSTIBLESpecification()
    	{
    
    	}
    
    	/// <summary>
    	/// Initializes a new instance of the <see cref="T_M_TIPO_TARJETA_COMBUSTIBLESpecification"/> class.
    	/// </summary>
    	/// <param name="initializeNavigationProperties">if set to <c>true</c> initialize navigation properties.</param>
    	public T_M_TIPO_TARJETA_COMBUSTIBLESpecification(bool initializeNavigationProperties)
    	{
    		if(!initializeNavigationProperties)
    			return;
    
    		this.T_M_TARJETAS_CONBUSTIBLE = new T_M_TARJETAS_CONBUSTIBLESpecification();
    	}
    
        #region ISpecification Members
    
    	public Expression<Func<T_M_TIPO_TARJETA_COMBUSTIBLE, bool>> GetExpression()
    	{
    		Expression<Func<T_M_TIPO_TARJETA_COMBUSTIBLE, bool>> expression = x => true;
    
    		if(ID_TARJETA_COMBUSTIBLE.HasValue)
    			expression = expression.And(x => x.ID_TARJETA_COMBUSTIBLE == ID_TARJETA_COMBUSTIBLE.Value);
    
    		if(ID_TARJETA_COMBUSTIBLEIN != null && ID_TARJETA_COMBUSTIBLEIN.Count() > 0)
    			expression = expression.And(x => ID_TARJETA_COMBUSTIBLEIN.Contains(x.ID_TARJETA_COMBUSTIBLE));
    	
    		if(ID_TARJETA_COMBUSTIBLEFrom.HasValue)
    			expression = expression.And(x => x.ID_TARJETA_COMBUSTIBLE >= ID_TARJETA_COMBUSTIBLEFrom.Value);
    			
    		if(ID_TARJETA_COMBUSTIBLETo.HasValue)
    			expression = expression.And(x => x.ID_TARJETA_COMBUSTIBLE <= ID_TARJETA_COMBUSTIBLETo.Value);
    				
    
    	
    		if(!string.IsNullOrWhiteSpace(DESCRIPCION))  
    			expression = expression.And(x => x.DESCRIPCION.Equals(DESCRIPCION));
    			
    		if(!string.IsNullOrWhiteSpace(DESCRIPCIONContains))  
    			expression = expression.And(x => x.DESCRIPCION.Contains(DESCRIPCIONContains));
    			
    		if(!string.IsNullOrWhiteSpace(DESCRIPCIONStartsWith))
    			expression = expression.And(x => x.DESCRIPCION.StartsWith(DESCRIPCIONStartsWith));
    
    		if(!string.IsNullOrWhiteSpace(DESCRIPCIONEndsWith))
    			expression = expression.And(x => x.DESCRIPCION.EndsWith(DESCRIPCIONEndsWith));
    
    		if(DESCRIPCIONIN != null && DESCRIPCIONIN.Count() > 0)
    			expression = expression.And(x => DESCRIPCIONIN.Contains(x.DESCRIPCION));
    
    		if(BAJA.HasValue)
    			expression = expression.And(x => x.BAJA == BAJA.Value);
    
    		if(BAJAIN != null && BAJAIN.Count() > 0)
    			expression = expression.And(x => BAJAIN.Contains(x.BAJA));
    		
    		//
    		// Navigation properties
    		//
    
    		if(this.T_M_TARJETAS_CONBUSTIBLE != null)
    		{
    			var subExpression = T_M_TARJETAS_CONBUSTIBLE.GetExpression();
    			expression = expression.And(x => x.T_M_TARJETAS_CONBUSTIBLE.AsQueryable().Any(subExpression));
    		}
    	
    		return expression;
    	}
    	
    	public bool IsSatisfiedBy(T_M_TIPO_TARJETA_COMBUSTIBLE entity)
    	{
    		// convert single entity to a IQueryable object, 
    		// in order to be able to use lambda expressions
    		IQueryable<T_M_TIPO_TARJETA_COMBUSTIBLE> entities = (new[] { entity }).AsQueryable();
    		
    		return entities.Any(this.GetExpression());
    	}
    
        public override string ToString()
        {
            return Evaluator.PartialEval(this.GetExpression()).ToString();
        }

        #endregion

    }
}
